#include <Arduino.h>

#define NB_POSITIONS 6

#define BKGD 0x218d
#define GEAR 0xfffc
#define CNTR 0xfa0c

static const uint16_t PROGMEM image_data_gear[NB_POSITIONS][256] = {
  { // ░░░░░░░░░░░░░░░░
    // ░░█░░░░██░░░░█░░
    // ░███░░░██░░░███░
    // ░░████████████░░
    // ░░░██████████░░░
    // ░░░███▒▒▒▒███░░░
    // ░░░██▒▒▒▒▒▒██░░░
    // ░████▒▒░░▒▒████░
    // ░████▒▒░░▒▒████░
    // ░░░██▒▒▒▒▒▒██░░░
    // ░░░███▒▒▒▒███░░░
    // ░░░██████████░░░
    // ░░████████████░░
    // ░███░░░██░░░███░
    // ░░█░░░░██░░░░█░░
    // ░░░░░░░░░░░░░░░░
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD,
    BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD },

  { // ░░░░█░░░░░░░░░░░
    // ░░░██░░░░░░░░░░░
    // ░░░░██░░░██░░░░░
    // ░░░░░██████░░░░█
    // ░░░░████████░░██
    // ░░░░███▒▒██████░
    // ░░████▒▒▒▒▒███░░
    // ░░████▒▒░▒▒▒██░░
    // ░░░██▒▒░░░▒▒██░░
    // ░░░██▒▒▒░▒▒████░
    // ░░░███▒▒▒▒▒████░
    // ░░██████▒▒███░░░
    // ███░█████████░░░
    // ░█░░░░██████░░░░
    // ░░░░░░██░░░██░░░
    // ░░░░░░░░░░░░██░░
    BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, GEAR, GEAR,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, CNTR, CNTR, CNTR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, CNTR, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    GEAR, GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD },

  { // ░░░░░░██░░░░░░░░
    // ░░░░░░███░░░░░░░
    // ░░░░░░███░░█░░░░
    // ░░░░░░███░███░░░
    // ░░░█░░██████░░░░
    // ░░██████▒████░░░
    // ░░░███▒▒▒▒▒█████
    // ░░░███▒▒░▒▒█████
    // ░████▒▒░░░▒▒███░
    // ██████▒▒░▒▒███░░
    // ██████▒▒▒▒▒███░░
    // ░░░░████▒██████░
    // ░░░░░███████░█░░
    // ░░░░███████░░░░░
    // ░░░░░█░░███░░░░░
    // ░░░░░░░░░██░░░░░
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, GEAR, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR,
    BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD,
    GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD },

  { // ░░░░░░░███░░░░░░
    // ░░░░░░░███░░░░░░
    // ░░░░█░░███░░░░░░
    // ░░░██░█████░██░░
    // ░░░██████▒███░░░
    // ░░░░███▒▒▒███░░░
    // ██████▒▒▒▒▒▒████
    // █████▒▒▒░░▒▒████
    // █████▒▒░░▒▒▒████
    // ░░███▒▒▒▒▒▒███░░
    // ░░░░███▒▒▒███░░░
    // ░░░░███▒██████░░
    // ░░░██░█████░██░░
    // ░░░░█░░███░░█░░░
    // ░░░░░░░███░░░░░░
    // ░░░░░░░███░░░░░░
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR,
    GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR,
    GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR,
    BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD },

  { // ░░░░░░░░░██░░░░░
    // ░░░░░░░░░██░░░░░
    // ░░░░░█░░███░░░░░
    // ░░░░████████░░░░
    // ░░░░░███████░█░░
    // ██░█████▒██████░
    // ██████▒▒▒▒▒███░░
    // ░█████▒▒░▒▒███░░
    // ░░░██▒▒░░░▒▒███░
    // ░░░███▒▒░▒▒█████
    // ░░░███▒▒▒▒▒█████
    // ░░██████▒████░░░
    // ░░░█░███████░░░░
    // ░░░░░░███░███░░░
    // ░░░░░░██░░░█░░░░
    // ░░░░░░██░░░░░░░░
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, GEAR, BKGD, BKGD,
    GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD,
    GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR,
    BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD },

  { // ░░░░░░░░░░░░█░░░
    // ░░░░░░██░░░███░░
    // ░░░░░░██░░███░░░
    // ░█░░░░██████░░░░
    // ███░█████████░░░
    // ░███████▒▒███░░░
    // ░░████▒▒▒▒▒████░
    // ░░░██▒▒▒░▒▒████░
    // ░░░██▒▒░░░▒▒██░░
    // ░░████▒▒░▒▒▒██░░
    // ░░████▒▒▒▒▒███░░
    // ░░░░███▒▒██████░
    // ░░░░████████░░██
    // ░░░░░██████░░░░█
    // ░░░░██░░░██░░░░░
    // ░░░██░░░░░░░░░░░
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD,
    GEAR, GEAR, GEAR, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, CNTR, BKGD, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, CNTR, CNTR, BKGD, BKGD, BKGD, CNTR, CNTR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, BKGD, CNTR, CNTR, CNTR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, CNTR, CNTR, CNTR, CNTR, CNTR, GEAR, GEAR, GEAR, BKGD, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, CNTR, CNTR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, GEAR, GEAR,
    BKGD, BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, GEAR, GEAR, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, GEAR,
    BKGD, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD,
    BKGD, BKGD, BKGD, GEAR, GEAR, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD, BKGD }
};