#ifndef Robo_communication_h
#define Robo_communication_h

#include <Arduino.h>
#include <Wire.h>

#define NB_ROBOTS 4
#define NB_MATRIX_MODES 6
#define NB_SPOTLIGHT_MODES 4

#define DRUM_ADDRESS 1
#define GLOCKEN_ADDRESS 2
#define MUSIC_BOX_ADDRESS 3
#define LIGHTING_ADDRESS 4

#define MATRIX 0
#define SPOTLIGHT 1

enum MessageType {
  START,
  RESYNC,
  BPM_CHANGE,
  MODE_CHANGE,  
  SET_RESYNC_TIME  
};

#define MATRIX_OFF_MODE 0
#define MATRIX_BLINKING_MODE 1
#define MATRIX_NAME_MODE 2
#define MATRIX_LOGO_MODE 3
#define MATRIX_RECTANGLES_MODE 4
#define MATRIX_BARS_MODE 5

#define SPOTLIGHT_OFF_MODE 0
#define SPOTLIGHT_BLINKING_MODE 1
#define SPOTLIGHT_SEQUENCE_MODE 2
#define SPOTLIGHT_CONSTANT_MODE 3

inline uint8_t robotAddresses[NB_ROBOTS] = {DRUM_ADDRESS, GLOCKEN_ADDRESS, MUSIC_BOX_ADDRESS, LIGHTING_ADDRESS};
inline uint8_t spotlightModes[NB_SPOTLIGHT_MODES] = {SPOTLIGHT_OFF_MODE, SPOTLIGHT_BLINKING_MODE, SPOTLIGHT_SEQUENCE_MODE, SPOTLIGHT_CONSTANT_MODE};
inline uint8_t matrixModes[NB_MATRIX_MODES] = {MATRIX_OFF_MODE, MATRIX_BLINKING_MODE, MATRIX_NAME_MODE, MATRIX_LOGO_MODE, MATRIX_RECTANGLES_MODE, MATRIX_BARS_MODE};

#define MASK_BYTE0 0x00FF
#define MASK_BYTE1 0xFF00

#define MASK_LIGHTING_MODE 0b11111110
#define MASK_ELEMENT_IDENTIFIER 0b00000001
#define BITS_PER_ELEMENT_IDENTIFIER 1

#define BITS_PER_BYTE 8
#define BYTES_PER_UINT8 1
#define BYTES_PER_UINT16 2


#endif