#ifndef Robo_communication_h
#define Robo_communication_h

#include <Arduino.h>
#include <Wire.h>

#define NB_ROBOTS 5

enum RobotAdress {
  DRUM_ADDRESS = 1,
  GLOCKEN_ADDRESS,
  MUSIC_BOX_ADDRESS,
  LIGHTING_ADDRESS,
  SINGER_ADDRESS
};

inline const uint8_t _robotAddress[NB_ROBOTS] = {DRUM_ADDRESS, GLOCKEN_ADDRESS, MUSIC_BOX_ADDRESS, LIGHTING_ADDRESS, SINGER_ADDRESS};

enum Robots {
  DRUM_ROBOT,
  GLOCKEN_ROBOT,
  MUSIC_BOX_ROBOT,
  LIGHTING_ROBOT,
  SINGER_ROBOT
};

#define NB_SONGS 3

enum Songs {
  FRERE_JACQUES,
  HOUND_DOG,
  SMOKE,
  SMELLS_LIKE,
  SEVEN_NATION,
  HARRY_POTTER,
  MR_SANDMAN_LONG,
  MR_SANDMAN_SHORT,
  BASIC_RYTHM,
  COOLEST_RYTHM,
  PUN_TAS
};

inline const uint8_t _songs[NB_SONGS] = {MR_SANDMAN_LONG, MR_SANDMAN_SHORT, HOUND_DOG};

#define MATRIX 0
#define SPOTLIGHT 1

#define DEFAULT_BPM 90
#define DEFAULT_BPM_IDX 17
#define NB_BPM_VALUES 29
#define DEFAULT_RESYNC_TIME 2000

enum MessageType {
  START,
  START_SONG,
  STOP,
  RESYNC,
  BPM_CHANGE,
  BPM_IDX_CHANGE,
  MTX_MODE_CHANGE,
  SPL_MODE_CHANGE,
  MTX_BLINK_CHANGE,
  SPL_BLINK_CHANGE,
  BRIGHTNESS_CHANGE,
  LIMB_STOP,
  LIMB_START,
  NOTE_ON,
  NOTE_OFF,
  VIBRATO_AMP_CHANGE,
  SET_RESYNC_TIME
};

enum MatrixModes {
  MTX_OFF_MODE,
  MTX_CONSTANT_MODE,
  MTX_BLINK_MODE,
  MTX_NAME_MODE,
  MTX_LOGO_MODE,
  MTX_RCT_MODE,
  MTX_BARS_MODE
};

enum SpotlightModes {
  SPL_TOP_ON,
  SPL_TOP_OFF,
  SPL_BOTTOM_ON,
  SPL_BOTTOM_OFF,
  SPL_BLINK_ON,
  SPL_BLINK_OFF,
  SPL_SEQ_ON,
  SPL_SEQ_OFF
};

enum BlinkingIntervals {
  WHOLE_INTERVAL,
  HALF_INTERVAL,
  QUARTER_INTERVAL,
  QUAVER_INTERVAL,
  SEMIQUAVER_INTERVAL
};

#define MASK_BYTE0 0x00FF
#define MASK_BYTE1 0xFF00

#define BITS_PER_BYTE 8
#define BYTES_PER_UINT8 1
#define BYTES_PER_UINT16 2

#endif